train_dir: C:\Son\Dataset\train
eval_dir: C:\Son\Dataset\eval
test_dir: C:\Son\Dataset\test


result_dir: ./results/baseline
model_dir: ./model/baseline

model_path: baseline.pth

epochs: 100
batch_size: 64
lr: 1e-3

gpu: 0
n_workers: 4

sr: 16000
n_fft: 1024
win_length: 1024
hop_length: 512
n_mels: 128
power: 2.0
