train_dir: /content/drive/My Drive/2025AIChallenge/Dataset/train
eval_dir: /content/drive/My Drive/2025AIChallenge/Dataset/eval
test_dir: /content/drive/My Drive/2025AIChallenge/Dataset/test


result_dir: ./results/baseline
model_dir: ./model/baseline

model_path: baseline.pth

epochs: 100
batch_size: 64
lr: 1e-3

gpu: 0
n_workers: 2

sr: 16000
n_fft: 1024
win_length: 1024
hop_length: 512
n_mels: 128
power: 2.0
